Description:
  This will create a web ACL with AWS Managed Ruleset (Common Rule Set)
  enabled and exluding a rule inside it.
Resources:
  SampleIPSet:
    Type: AWS::WAFv2::IPSet
    Properties:
      Description: SampleIPSet
      Name: SampleIPSet
      Scope: CLOUDFRONT
      IPAddressVersion: IPV4
      Addresses:
        - 1.2.1.1/32
  WebACLWithAMR:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: WebACLWithAMR
      Scope: CLOUDFRONT
      Description: ACL with AWS Managed Rules
      DefaultAction:
        Allow: {}
      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: MetricForWebACLWithAMR
      Tags:
        - Key: !Sub "${AWS::StackName}"
          Value: WAF
      Rules:
        - Name: AWS-AWSManagedRulesCommonRuleSet
          Priority: 0
          OverrideAction:
            Count: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: MetricForAMRCRS
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet
              ExcludedRules:
                - Name: NoUserAgent_HEADER
        - Name: IPSetWithException
          Priority: 1
          Action:
            Count: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: IPSetWithExceptionMetric
          Statement:
            AndStatement:
              Statements:
                - IPSetReferenceStatement:
                    ARN: !GetAtt "SampleIPSet.Arn"
                - NotStatement:
                    Statement:
                      ByteMatchStatement:
                        FieldToMatch:
                          SingleHeader:
                            Name: host
                        PositionalConstraint: EXACTLY
                        SearchString: dev.appleorange.com
                        TextTransformations:
                          - Type: NONE
                            Priority: 0
Outputs:
  WebAclArn:
    Description: WAF WebAcl Arn for WAFv2
    Value: !GetAtt "WebACLWithAMR.Arn"
  WebAclId:
    Description: WAF WebAcl Id for WAF Classic
    Value: !GetAtt "WebACLWithAMR.Id"
